In [5]:
import json
import pandas as pd
import os

#Ruta de lectura
path = r"C:\Users\Alonso\Desktop\CDIA_NLP\connect_deephub\results_data\data_v9"

#Lectura de data
filepath=os.path.join(path, "data_translated_concat.xlsx")
df_old = pd.read_excel(filepath)

#Ruta de lectura
path = r"C:\Users\Alonso\Desktop\CDIA_NLP\final_proyecto"

#Lectura de data
filepath=os.path.join(path, "data_translated.csv")
df_new = pd.read_csv(filepath)

In [6]:
codigos_faltantes = df_old.loc[~df_old["Código VRID"].isin(df_new["Código VRID"])]

print(codigos_faltantes)

Empty DataFrame
Columns: [Código VRID, Interdisciplinario, Transdisciplinario, Título, Keywords, Resumen, Facultad del Proyecto, Depto Persona, Titulo_trad, Resumen_trad, keywords_trad, Facultad_del_Proyecto_trad, Depto_Persona_trad, Español, text_for_embedding_translated]
Index: []

In [ ]:
df_merged = df_old.merge(
    df_new[["Código VRID", "Titulo_trad", "Resumen_trad", "keywords_trad"]],
    on="Código VRID",
    how="left",
    suffixes=("_old", "_new")
)
# Filtrar donde alguna de las columnas no coincide
diferencias = df_merged[
    (df_merged["Titulo_trad_old"] != df_merged["Titulo_trad_new"]) |
    (df_merged["Resumen_trad_old"] != df_merged["Resumen_trad_new"]) |
    (df_merged["keywords_trad_old"] != df_merged["keywords_trad_new"])
]

diferencias.head()

# Titulo

In [17]:
df_merged = df_old.merge(
    df_new[["Código VRID", "Titulo_trad"]],
    on="Código VRID",
    how="left",
    suffixes=("_old", "_new")
)
df_merged = df_merged[["Código VRID", "Titulo_trad_old", "Titulo_trad_new"]]

In [28]:
df_diff = df_merged[df_merged["Titulo_trad_old"] != df_merged["Titulo_trad_new"]]
df_diff

,Código VRID,Titulo_trad_old,Titulo_trad_new
7,010/2023,model migration of nothofagus obliqua in respo...,model migration of nothofagus obliqua in respo...
10,018/2019,implementation and evaluation of ecological re...,implementation and evaluation of ecological re...
13,101084511,jean monnet chair: 'centre for european studie...,Jean monnet chair: 'Centre for European Studie...
17,11190637,transgenerational and within-generation plasti...,transgenerational and within-generation plasti...
31,11200853,assessing the environmental impact of the high...,assessing the environmental impact of the high...
...,...,...,...
1012,PYT-2021-0399,"implementation of the food hub model, for the ...","implementation of the food hub model, for the ..."
1031,RT_23-19,decoding the viroma of penguins to understand ...,decoding the viroma of penguins to understand ...
1036,TA23I10031,sustainable processing of copper concentrates:...,Sustainable processing of copper concentrates:...
1044,TRANSELEC,ecological restoration project in the national...,ecological restoration project in the National...
1079,VIU24P0097,marking-free biosensor for detection of saxito...,Marking-free biosensor for detection of saxito...

In [30]:
idx = 1012
print(df_merged.iloc[idx]["Titulo_trad_old"])
print(df_merged.iloc[idx]["Titulo_trad_new"])

implementation of the food hub model, for the strengthening and optimization of the production and marketing process of the casteño sector of the ñuble region
implementation of the food hub model, for the strengthening and optimization of the production and marketing process of the Casteño sector of the ñuble region

In [32]:
path = r"C:\Users\Alonso\Desktop\CDIA_NLP\final_proyecto\comparacion_old_new"
savepath = os.path.join(path,"diff.xlsx")
df_diff.to_excel(savepath)

# Keywords

In [36]:
df_merged = df_old.merge(
    df_new[["Código VRID", "keywords_trad"]],
    on="Código VRID",
    how="left",
    suffixes=("_old", "_new")
)
df_merged = df_merged[["Código VRID", "keywords_trad_old", "keywords_trad_new"]]

In [40]:
df_diff = df_merged[df_merged["keywords_trad_old"] != df_merged["keywords_trad_new"]]

In [39]:
path = r"C:\Users\Alonso\Desktop\CDIA_NLP\final_proyecto\comparacion_old_new"
savepath = os.path.join(path,"diff_keys.xlsx")
df_diff.to_excel(savepath)

# Resumen

In [41]:
df_merged = df_old.merge(
    df_new[["Código VRID", "Resumen_trad"]],
    on="Código VRID",
    how="left",
    suffixes=("_old", "_new")
)
df_merged = df_merged[["Código VRID", "Resumen_trad_old", "Resumen_trad_new"]]

In [43]:
df_diff = df_merged[df_merged["Resumen_trad_old"] != df_merged["Resumen_trad_new"]]
df_diff

,Código VRID,Resumen_trad_old,Resumen_trad_new
0,2023-059,in a research program that seeks to contribute...,In a research program that seeks to contribute...
1,40044450,the district of innovation of ñuble is a proje...,the district of innovation of ñuble is a proje...
2,#2024-5501,NaN,general objectives: to describe the processes ...
6,010/2022,the endemic species of the archipelago juan fe...,the endemic species of the archipelago juan fe...
7,010/2023,this project consists of elaborating a model t...,This project consists of elaborating a model t...
...,...,...,...
1078,VIU24P0041,the loss of bone tissue caused by lesions of t...,the loss of bone tissue caused by lesions of t...
1079,VIU24P0097,"the events of harmful algale blooms (fan), bet...","the events of harmful algale blooms (fan), bet..."
1080,VIU24P0120,production and human life generate a quantity ...,production and human life generate a quantity ...
1081,VIU24P0127,"at present, the basic courses of electrical ma...","At present, the basic courses of electrical ma..."
1082,VIU24P0144,copper mining is crucial for the chilean econo...,copper mining is crucial for the Chilean econo...

In [44]:
path = r"C:\Users\Alonso\Desktop\CDIA_NLP\final_proyecto\comparacion_old_new"
savepath = os.path.join(path,"diff_Resumen.xlsx")
df_diff.to_excel(savepath)