# Config

In [1]:
!git config --global --add safe.directory /tmp/Repository/VRID_language_proyect

In [2]:
import os

# Ruta a la que quieres mover el path
nueva_ruta = "/tmp/Repository/VRID_language_proyect/BERT"

# Cambiar el directorio actual
os.chdir(nueva_ruta)

# Confirmar que cambió
print("Directorio actual:", os.getcwd())

Directorio actual: /tmp/Repository/VRID_language_proyect/BERT

In [3]:
import pandas as pd
import os
import numpy as np

# Cargar datos

In [ ]:
# 1) Cargar datos antiguos
path = "/tmp/ocde/new_data"

#Cargar titulo, keys, etc.
filePATH = os.path.join(path, "old_data.xlsx")
df_data = pd.read_excel(filePATH, usecols=["Código VRID", "Título", "Keywords", "Resumen", "Depto Persona",
                                           "Facultad del Proyecto", "Interdisciplinario", "Transdisciplinario"])


# 2) Textos nuevos
#Pagina 0
filePATH = os.path.join(path, "new_data.xlsx")
df_new0 = pd.read_excel(os.path.join(path, filePATH), usecols=["Código VRID", "Título", "Keywords", "Resumen"], sheet_name=0)
df_new1 = pd.read_excel(os.path.join(path, filePATH), usecols=["Código VRID", "Título", "Keywords", "Resumen"], sheet_name=1)

df_new = pd.concat([df_new0, df_new1])

# 3) Etiquedas Datos OCDE y ODS
#Pagina 2
df_ocde0 = pd.read_excel(os.path.join(path, filePATH), usecols=["Código VRID", "Categoria Disciplina", 
                                             "Sub Area Disciplina", "Tipo Área Disciplina"], sheet_name=2)
#Pagina 3
df_ocde1 =  pd.read_excel(os.path.join(path, filePATH), usecols=["Código VRID", "Categoria Disciplina", 
                                             "Sub Area Disciplina", "Tipo Área Disciplina"], sheet_name=3)

df_labels = pd.concat([df_ocde0, df_ocde1])


# 4) Desafíos país
path = "/tmp/desafios/new_data"
filePATH = os.path.join(path, "Datos_DP.xlsx")
df_labels_desafios = pd.read_excel(filePATH, usecols=["Código VRID", "Desafío País"])

# 5) Lineas de investigación
path = "/tmp/data/"
#Cargar titulo, keys, etc.
filePATH = os.path.join(path, "data_lineas_investigacion.xlsx")
df_data_lineas = pd.read_excel(filePATH, 
                        usecols=["Código VRID", "Título", "Keywords", "Resumen", 
                                 "Línea de investigación"]).drop_duplicates("Código VRID")

In [ ]:
df_all = pd.concat([df_data["Código VRID"], df_new["Código VRID"], df_labels["Código VRID"],
                    df_labels_desafios["Código VRID"], df_data_lineas["Código VRID"]])
print(df_all.shape)
df_all = df_all.drop_duplicates()
print("Cantidad total de textos:", df_all.shape)

(5179,)
Cantidad total de textos: (1991,)

In [5]:
# 1) Cargar datos antiguos
path = "/tmp/ocde/new_data"

#Cargar titulo, keys, etc.
filePATH = os.path.join(path, "old_data.xlsx")
df_data = pd.read_excel(filePATH, usecols=["Código VRID", "Título", "Keywords", "Resumen", "Depto Persona",
                                           "Facultad del Proyecto", "Interdisciplinario", "Transdisciplinario"])

# 2) Textos nuevos
#Pagina 0
filePATH = os.path.join(path, "new_data.xlsx")
df_new0 = pd.read_excel(os.path.join(path, filePATH), usecols=["Código VRID", "Título", "Keywords", "Resumen"], sheet_name=0)
df_new1 = pd.read_excel(os.path.join(path, filePATH), usecols=["Código VRID", "Título", "Keywords", "Resumen"], sheet_name=1)

df_new = pd.concat([df_new0, df_new1])

# 3) Etiquedas Datos OCDE y ODS
#Pagina 2
df_ocde0 = pd.read_excel(os.path.join(path, filePATH), usecols=["Código VRID", "Categoria Disciplina", 
                                             "Sub Area Disciplina", "Tipo Área Disciplina"], sheet_name=2)
#Pagina 3
df_ocde1 =  pd.read_excel(os.path.join(path, filePATH), usecols=["Código VRID", "Categoria Disciplina", 
                                             "Sub Area Disciplina", "Tipo Área Disciplina"], sheet_name=3)

df_labels = pd.concat([df_ocde0, df_ocde1])

# 4) Desafíos país
path = "/tmp/desafios/new_data"
filePATH = os.path.join(path, "Datos_DP.xlsx")
df_labels_desafios = pd.read_excel(filePATH, usecols=["Código VRID", "Desafío País"])

In [13]:
print(np.unique(df_data["Código VRID"].astype(str)).shape)
print(np.unique(df_new["Código VRID"].astype(str)).shape)
print(np.unique(df_labels["Código VRID"].astype(str)).shape)
print(np.unique(df_labels_desafios["Código VRID"].astype(str)).shape)

(1083,)
(1397,)
(565,)
(1404,)

In [14]:
df_old_new = pd.concat([df_data, df_new])
print(np.unique(df_old_new["Código VRID"].astype(str)).shape)

(1410,)

In [20]:
dic1 = {
    "code": [0, 1, 2, 3, 4],
    "elements": ["Hola", "Hola", "Hola", "Hola", "Hola"]
}

dic2 = {
    "code": [5, 6, 1, 7, 8],
    "elements": ["chao", "chao", "chao", "chao", "chao"]
}

df1 = pd.DataFrame(dic1)
df2 = pd.DataFrame(dic2)

# Merge en base a "Código VRID"
df_merged = pd.merge(
    df1,
    df2,
    on="code",       # columna clave
    how="outer"             # inner = solo los que coinciden en ambos
)
df_merged

   code elements_x elements_y
0     0       Hola        NaN
1     1       Hola       chao
2     2       Hola        NaN
3     3       Hola        NaN
4     4       Hola        NaN
5     5        NaN       chao
6     6        NaN       chao
7     7        NaN       chao
8     8        NaN       chao

In [22]:
df_merged["elements"] = df_merged["elements_x"].combine_first(df_merged["elements_y"])
df_merged

   code elements_x elements_y elements
0     0       Hola        NaN     Hola
1     1       Hola       chao     Hola
2     2       Hola        NaN     Hola
3     3       Hola        NaN     Hola
4     4       Hola        NaN     Hola
5     5        NaN       chao     chao
6     6        NaN       chao     chao
7     7        NaN       chao     chao
8     8        NaN       chao     chao